#!/usr/bin/env python3

import os
import socket
import sys
import argparse

socketpath = '/tmp/minecraft-ctl'
quiet = False

#def deadcode():
	#if os.path.exists(sys.argv[1]) and not os.path.isdir(sys.argv[1]) and not os.path.isfile(sys.argv[1]):
		#socketpath = sys.argv[1]
		#cmd = b' '.join(map(lambda x: x.encode(), sys.argv[2:]))
	#else:
		#socketpath = '/tmp/minecraft-ctl'
		#cmd = b' '.join(map(lambda x: x.encode(), sys.argv[1:]))

class SocketError(Exception):
	pass

def get_command(args):
	return b' '.join(map(lambda x: x.encode(), args.command))

def check_socket():
	if not os.path.exists(socketpath):
		raise SocketError("%s is missing - is the minecraft server running?" % socketpath)

def connect():
	s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
	try:
		s.connect(socketpath)
	except socket.error:
		raise SocketError("could not connect to %s - is the minecraft server running?" % socketpath)
	return s

def send_command(command):
	try:
		check_socket()
		sock = connect()
		sock.send(command + b"\n")
		data = sock.recv(1024)
		sock.close()
		if data:
			print(data.decode())
	except SocketError as ex:
		if not quiet:
			print('Error: '+str(ex))
		sys.exit(1)

def check_server():
	try:
		check_socket()
		sock = connect()
		sys.exit(0)
	except SocketError:
		sys.exit(1)

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument('command', metavar='COMMAND', type=str, nargs='*', help='command to execute')
	parser.add_argument('--mode', default='execute', help='either "check" or "execute"')
	parser.add_argument('-q', '--quiet', action='store_true')
	args = parser.parse_args()
	quiet = args.quiet

	if args.mode == 'command' and not args.command:
		print("ERROR: missing command")
		sys.exit(1)
	if  args.mode == 'check':
		check_server()
	else:
		send_command(get_command(args))
