#!/usr/bin/env python

from __future__ import print_function

import os
import socket
import sys

def main():
	if len(sys.argv) < 2:
		print("ERROR: missing arguments")
		sys.exit(1)

	if os.path.exists(sys.argv[1]) and not os.path.isdir(sys.argv[1]) and not os.path.isfile(sys.argv[1]):
		socketpath = sys.argv[1]
		cmd = b' '.join(map(lambda x: x.encode(), sys.argv[2:]))
	else:
		socketpath = '/tmp/minecraft-ctl'
		cmd = b' '.join(map(lambda x: x.encode(), sys.argv[1:]))

	if not os.path.exists(socketpath):
		print("ERROR: %s is missing - is the minecraft server running?" % socketpath)
		sys.exit(1)

	s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)

	try:
		s.connect(socketpath)
	except socket.error:
		print("ERROR: could not connect to %s - is the minecraft server running?" % socketpath)
		sys.exit(1)

	s.send(cmd + b"\n")

	data = s.recv(1024)
	s.close()
	if data:
		print(data.decode())


main()
