#!/usr/bin/env python

import os
import sys
import socket
import select
import subprocess
import pwd
import signal

do_daemonize = False

for arg in sys.argv[1:]:
	if arg == '--daemonize':
		do_daemonize = True
	elif os.path.isdir(arg):
		os.chdir(arg)
	else:
		print arg, 'is not a directory'
		sys.exit(1)

sys.path.insert(0, '')
import ctloptions as options


listensock = None
poll = select.poll()
clients = {}
proc = None
logfile = None

class SigTermException(Exception):
	pass


def log(msg):
	if not do_daemonize:
		print msg
	logfile.write("ctl: %s\n" % msg)

def listen():
	global listensock
	listensock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
	try:
		os.remove(options.socket)
	except OSError:
		pass
	listensock.bind(options.socket)
	listensock.listen(1)
	poll.register(listensock.fileno(), select.POLLIN | select.POLLERR | select.POLLHUP)

def accept():
	conn, addr = listensock.accept()
	clients[conn.fileno()] = conn
	poll.register(conn.fileno(), select.POLLIN | select.POLLERR | select.POLLHUP)

def readctl(fd):
	conn = clients[fd]
	data = conn.recv(1024)
	if not data:
		return
	proc.stdin.write(data)
	#conn.send("OK")
	conn.close()
	poll.unregister(fd)
	del clients[fd]
	return

def start_minecraft():
	global proc
	os.chdir(options.dir)
	cmd = [options.java]
	cmd.extend(options.jvmargs)
	cmd.extend(["-jar", options.serverjar])
	cmd.extend(options.serverargs)
	proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=logfile, stderr=subprocess.STDOUT)

def open_log():
	global logfile
	logfile = open(options.logfile, 'a+')

def setup_signals():
	def handler(signum, frame):
		raise SigTermException
	signal.signal(signal.SIGTERM, handler)

def write_pidfile():
	pidfile = open(options.pidfile, 'w+')
	pidfile.write(str(os.getpid()))
	pidfile.close()

def change_user():
	if os.getuid() == 0:
		uid = pwd.getpwnam(options.user)[2]
		os.setuid(uid)

def daemonize():
	if os.fork() != 0:
		os._exit(0)

	os.setsid()

	if os.fork() != 0:
		os._exit(0)

	sys.stdout = logfile
	sys.stderr = logfile
	sys.stdin = open('/dev/null', 'r')

	write_pidfile()

def mainloop():
	while True:
		events = poll.poll(5000) # 5 sec
		for event in events:
			if event[1] == select.POLLIN:
				if event[0] == listensock.fileno():
					accept()
				else:
					readctl(event[0])
			elif event[1] == select.POLLHUP:
				if event[0] == listensock.fileno():
					raise Exception("wait, wat?")
				else:
					log("closing connection" + repr(event))
					clients[event[0]].close()
					poll.unregister(event[0])
			elif event[1] == select.POLLERR or event[1] == select.POLLNVAL:
				if event[0] == listensock.fileno():
					raise Exception("wait, wat?")
				else:
					log("connection error...")
					clients[event[0]].close()
					poll.unregister(event[0])
			else:
				log("unhandled poll event" + repr(event))
				raise Exception()

		# check if server is still running
		ret = proc.poll()
		if ret != None:
			log("server process died, exiting")
			sys.exit(1)

try:
	setup_signals()
	open_log()
	if do_daemonize:
		daemonize()
	change_user()
	start_minecraft()
	listen()
	mainloop()
except SigTermException:
	log('got SIGTERM, shutting down')
except KeyboardInterrupt:
	log('got SIGINT, shutting down')
finally:
	if proc and proc.poll() == None:
		log("shutting down minecraft server")
		proc.terminate()
	if listensock:
		listensock.close()
	try:
		os.remove(options.socket)
	except OSError:
		pass
